services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env
